# NUMPY ASSIGNMENT

In [142]:
import pandas as pd 
import numpy as np

In [143]:
def vander_func(x,N=len(x),increasing = False):
    if increasing == False:
        return np.column_stack([x**(N-i-1) for i in range(N)])
    elif increasing == True:
        return np.fliplr(np.column_stack([x**(N-i-1) for i in range(N)]))

In [144]:
x = np.array(range(5))
vander_func(x)

array([[  0,   0,   0,   0,   1],
       [  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]], dtype=int32)

In [145]:
x = np.array(range(5))
vander_func(x,increasing=True)

array([[  1,   0,   0,   0,   0],
       [  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256]], dtype=int32)

In [146]:
#   Question 2

In [147]:
def mov_avg(z,w):
    return np.convolve(z,np.ones(w),'valid')/w

In [148]:
z = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window = 3

In [149]:
mov_avg(z,window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])